// Auth
export const AUTH_SIGN_IN = 'AUTH_SIGNIN'
export const AUTH_USER_ID = 'AUTH_USER_ID'
export const AUTH_SIGN_OUT = 'AUTH_SIGNOUT'

// Game
export const GAME_CHANGE = 'GAME_CHANGE'
export const GAME_INVITE_LOADED = 'GAME_INVITES_LOADED'
export const GAME_ACTIVE_LOADED = 'GAME_ACTIVE_LOADED'
export const GAME_COMPLETE_LOADED = 'GAME_COMPELTE_LOADED'
